---
title: "Ebola Epidemic"
author: "Taiwo"
date: "8 December 2015"
output: html_document
---
# Preliminaries
```{r}
library(ggplot2)
library(lubridate)
```

## Load in Data

```{r }
eboladat<-read.csv("ebola_data_db_format.csv", as.is = c(3))
str(eboladat)
levels(eboladat$Indicator)
levels(eboladat$Country)
eboladat1<-eboladat[eboladat$Country=="Guinea"|eboladat$Country =="Sierra Leone"|eboladat$Country=="Liberia",]
eboladat1$Date<-ymd(eboladat1$Date)
indicators<-levels(eboladat1$Indicator)
eb.cfr.c.ebc<-eboladat1[eboladat1$Indicator == indicators[1],]
head(eb.cfr.c.ebc)
eb.cfr.cps.ebc<-eboladat1[eboladat1$Indicator == indicators[2],]
head(eb.cfr.cps.ebc)
eb.cfr.p.ebc<-eboladat1[eboladat1$Indicator == indicators[3],]
head(eb.cfr.p.ebc)
eb.cfr.s.ebc<-eboladat1[eboladat1$Indicator == indicators[4],]
head(eb.cfr.s.ebc)
eb.cumm.c.ebc<-eboladat1[eboladat1$Indicator == indicators[5],]
head(eb.cumm.c.ebc)
eb.cumm.c.ebd<-eboladat1[eboladat1$Indicator == indicators[6],]
head(eb.cumm.c.ebd)
eb.cumm.cps.ebc<-eboladat1[eboladat1$Indicator == indicators[7],]
head(eb.cumm.cps.ebc)
eb.cumm.cps.ebd<-eboladat1[eboladat1$Indicator == indicators[8],]
head(eb.cumm.cps.ebd)
eb.cumm.p.ebc<-eboladat1[eboladat1$Indicator == indicators[9],]
head(eb.cumm.p.ebc)
eb.cumm.p.ebd<-eboladat1[eboladat1$Indicator == indicators[10],]
head(eb.cumm.p.ebd)
eb.cumm.s.ebc<-eboladat1[eboladat1$Indicator == indicators[10],]
head(eb.cumm.s.ebc)
eb.cumm.s.ebc<-eboladat1[eboladat1$Indicator == indicators[11],]
head(eb.cumm.s.ebc)
eb.cumm.s.ebd<-eboladat1[eboladat1$Indicator == indicators[12],]
head(eb.cumm.s.ebd)
eb.n21.c.ebc<-eboladat1[eboladat1$Indicator == indicators[13],]
head(eb.n21.c.ebc)
eb.n7.c.ebc<-eboladat1[eboladat1$Indicator == indicators[14],]
head(eb.n7.c.ebc)
eb.n21.c.ebd<-eboladat1[eboladat1$Indicator == indicators[15],]
head(eb.n7.c.ebc)
```

## Exploratory Analysis

### Cumulative Confirmed Ebola Cases
```{r }
summary(eb.cumm.c.ebc$value)
hist(eb.cumm.c.ebc$value, col = "grey")
hist(eb.cumm.c.ebc$value[eb.cumm.c.ebc$Country=="Liberia"], col = "green")
hist(eb.cumm.c.ebc$value[eb.cumm.c.ebc$Country=="Guinea"], col = "red")
hist(eb.cumm.c.ebc$value[eb.cumm.c.ebc$Country=="Sierra Leone"], col = "blue")
eb.cumm.c.ebc$Country<-factor(eb.cumm.c.ebc$Country)
boxplot(eb.cumm.c.ebc$value~eb.cumm.c.ebc$Country)
ggplot(data=eb.cumm.c.ebc,aes(x=Date, y=value, colour=Country)) +geom_line(size = 1)+ labs(title="Sequence Chart Cumulative of Ebola Confirmed Cases")


```

### Number of Confirmed Ebola Cases in last 21 days
```{r }
summary(eb.n21.c.ebc$value)
hist(eb.n21.c.ebc$value, col = "grey")
hist(eb.n21.c.ebc$value[eb.n21.c.ebc$Country=="Liberia"], col = "green")
hist(eb.n21.c.ebc$value[eb.n21.c.ebc$Country=="Guinea"], col = "red")
hist(eb.n21.c.ebc$value[eb.n21.c.ebc$Country=="Sierra Leone"], col = "blue")
eb.n21.c.ebc$Country<-factor(eb.n21.c.ebc$Country)
boxplot(eb.n21.c.ebc$value~eb.n21.c.ebc$Country)
ggplot(data=eb.n21.c.ebc,aes(x=Date, y=value, colour=Country)) +geom_line(size = 1)+ labs(title="Sequence Chart of Number of Confirmed Ebola Cases in last 21 Days")

```

### Cumulative Confirmed Ebola Deaths
```{r }
summary(eb.cumm.c.ebd$value)
hist(eb.cumm.c.ebd$value, col = "grey")
hist(eb.cumm.c.ebd$value[eb.cumm.c.ebd$Country=="Liberia"], col = "green")
hist(eb.cumm.c.ebd$value[eb.cumm.c.ebd$Country=="Guinea"], col = "red")
hist(eb.cumm.c.ebd$value[eb.cumm.c.ebd$Country=="Sierra Leone"], col = "blue")
eb.cumm.c.ebd$Country<-factor(eb.cumm.c.ebd$Country)
boxplot(eb.cumm.c.ebd$value~eb.cumm.c.ebd$Country)
ggplot(data=eb.cumm.c.ebd,aes(x=Date, y=value, colour=Country)) +geom_line(size = 1)+ labs(title="Sequence Chart of Cumulative Confirmed Ebola Cases")

```


### Case Fatality Rate For Confirmed Ebola Cases

```{r, echo=FALSE}
summary(eb.cfr.c.ebc$value)
hist(eb.cfr.c.ebc$value, col = "grey")
hist(eb.cfr.c.ebc$value[eb.cfr.c.ebc$Country=="Liberia"], col = "green")
hist(eb.cfr.c.ebc$value[eb.cfr.c.ebc$Country=="Guinea"], col = "red")
hist(eb.cfr.c.ebc$value[eb.cfr.c.ebc$Country=="Sierra Leone"], col = "blue")
eb.cfr.c.ebc$Country<-factor(eb.cfr.c.ebc$Country)
boxplot(eb.cfr.c.ebc$value~eb.cfr.c.ebc$Country)
ggplot(data=eb.cfr.c.ebc,aes(x=Date, y=value, colour=Country)) +geom_line(size = 1)+ labs(title="Sequence Chart of Case Fatality Rate of  Confirmed Ebola Cases")

```

